[build]
  command = "yarn run build && yarn run export"
  publish = "out"
  functions = "functions/"

[dev]
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[[plugins]]
package = "netlify-plugin-cache-nextjs"